### ISSUE TITLE
Example of use ?

### ISSUE THREAD

**Issue by dceejay** [GeoTIFF/geotiff-layer-for-leaflet#2]
Hi

any more complete example of use ? how can I point to an existing local (to server) geotiff file for example ?

**Comment by DanielJDufour** [comment]
Hi, @dceejay . Great question.  Here's an example:
 - Source Code: https://github.com/GeoTIFF/georaster-layer-for-leaflet-example/blob/master/main.js
 - Live Demo: https://geotiff.github.io/georaster-layer-for-leaflet-example/

[GeoRasterLayer](https://github.com/GeoTIFF/georaster-layer-for-leaflet) is in the process of superseding [GeoTIFFLayer](https://github.com/GeoTIFF/geotiff-layer-for-leaflet).  GeoRasterLayer is under active development, uses web workers,  and will handle many types of rasters.  I apologize for any confusion.
  
I'm happy to answer any other questions you might have.

Have a good day.
